args_parser.h File Reference
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include statuses.h
Classes
struct Argument
Specifies console argument parametres: name, function and description.
Typedefs
typedef ArgsMode(* args_func) (const Argument args_dict[], const int args_dict_len, int *arg_i, const int argc, char *argv[], int *auto_level, ssize_t *output_cnt, const char **filename, bool *voice)
Enumerations
enum class ArgsMode { ERR = -1
, EXIT = 0
, CONTINUE = 1
 }
Specifies int main() returns.
Functions
Status::Statuses args_parse (int argc, char *argv[], int *auto_level, ssize_t *output_cnt, const char **filename, bool *voice)
Parses console arguments.
ArgsMode print_help (const Argument args_dict[], const int args_dict_len, int *arg_i, const int argc, char *argv[], int *auto_level, ssize_t *output_cnt, const char **filename, bool *voice)
Prints help.
ArgsMode set_level (const Argument args_dict[], const int args_dict_len, int *arg_i, const int argc, char *argv[], int *auto_level, ssize_t *output_cnt, const char **filename, bool *voice)
Sets auto max level.
ArgsMode set_symb_num (const Argument args_dict[], const int args_dict_len, int *arg_i, const int argc, char *argv[], int *auto_level, ssize_t *output_cnt, const char **filename, bool *voice)
Sets output symb num.
ArgsMode set_filename (const Argument args_dict[], const int args_dict_len, int *arg_i, const int argc, char *argv[], int *auto_level, ssize_t *output_cnt, const char **filename, bool *voice)
Sets filename.
ArgsMode enable_voice (const Argument args_dict[], const int args_dict_len, int *arg_i, const int argc, char *argv[], int *auto_level, ssize_t *output_cnt, const char **filename, bool *voice)
Enables voiceover.
Typedef Documentation
args_func
typedef ArgsMode(* args_func) (const Argument args_dict[], const int args_dict_len, int *arg_i, const int argc, char *argv[], int *auto_level, ssize_t *output_cnt, const char **filename, bool *voice)
Definition at line 21 of file args_parser.h.
Enumeration Type Documentation
ArgsMode
enum class ArgsMode [strong]
Specifies int main() returns.
Enumerator
ERR Error.
EXIT Continue reading args, but then normal exit.
CONTINUE Continue reading args.
Definition at line 13 of file args_parser.h.
                    {
    ERR = -1,
    EXIT = 0,
    CONTINUE = 1,
};
Function Documentation
args_parse()
Status::Statuses args_parse (int argc, char * argv[], int * auto_level, ssize_t * output_cnt, const char ** filename, bool * voice)
Parses console arguments.
Parameters
argc
argv
auto_level
output_cnt
filename
voice
Returns
Status::Statuses
This array contains console options, their functions and descriptions
< Set automat max level
< Set automat max level
< Set printed symbols num
< Enable voiceover
< Help option
< args_dict array len
Definition at line 3 of file args_parser.cpp.
                                                                                                      {
    assert(argv);
    assert(argc);
    assert(auto_level);
    assert(output_cnt);
    assert(filename);
    assert(voice);
    static Argument args_dict[] = {
        {"-f", set_filename, "# -f <name> - required - sets filename\n"},
        {"-l", set_level, "# -l <lvl> - required - sets automaton max level\n"},
        {"-n", set_symb_num, "# -n <num> - required - sets printed symbols number\n"},
        {"-v", enable_voice, "# -v - enables voiceover\n"},
        {"-h", print_help, "# -h - prints help information\n"},
    };
    static const int ARGS_DICT_LEN = sizeof(args_dict) / sizeof(args_dict[0]);
    bool exit = false;
    for (int i = 1; i < argc; i++) {
        bool is_found = false;
        for (int j = 0; j < ARGS_DICT_LEN; j++) {
            if (strcmp(argv[i], args_dict[j].arg) == 0) {
                switch (args_dict[j].func(args_dict, ARGS_DICT_LEN, &i, argc, argv, auto_level, output_cnt, filename, voice)) {
                    case ArgsMode::CONTINUE:
                        break;
                    case ArgsMode::EXIT:
                        exit = true;
                        break;
                    case ArgsMode::ERR:
                        return Status::ARGS_ERROR;
                    default:
                        assert(0 && "args[j].func() returned wrong ArgsMode");
                        break;
                }
                is_found = true;
                break;
            }
        }
        if (is_found)
            continue;
        printf("Wrong console argument: %s\n"
               "Use -h for help\n", argv[i]);
        return Status::ARGS_ERROR;
    }
    if (exit)
        return Status::OK_EXIT;
    return Status::NORMAL_WORK;
}
References Status::ARGS_ERROR, CONTINUE, enable_voice(), ERR, EXIT, Status::NORMAL_WORK, Status::OK_EXIT, print_help(), set_filename(), set_level(), and set_symb_num().
Referenced by main().
enable_voice()
ArgsMode enable_voice (const Argument args_dict[], const int args_dict_len, int * arg_i, const int argc, char * argv[], int * auto_level, ssize_t * output_cnt, const char ** filename, bool * voice)
Enables voiceover.
Parameters
args_dict
args_dict_len
arg_i
argc
argv
auto_level
output_cnt
filename
voice
Returns
ArgsMode
Definition at line 167 of file args_parser.cpp.
                                                                                                {
    (void) args_dict;
    (void) args_dict_len;
    (void) arg_i;
    (void) argc;
    (void) argv;
    (void) auto_level;
    (void) output_cnt;
    (void) filename;
    assert(args_dict);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(auto_level);
    assert(output_cnt);
    assert(filename);
    assert(voice);
    *voice = true;
    return ArgsMode::CONTINUE;
}
References CONTINUE.
Referenced by args_parse().
print_help()
ArgsMode print_help (const Argument args_dict[], const int args_dict_len, int * arg_i, const int argc, char * argv[], int * auto_level, ssize_t * output_cnt, const char ** filename, bool * voice)
Prints help.
Parameters
args_dict
args_dict_len
arg_i
argc
argv
auto_level
output_cnt
filename
voice
Returns
ArgsMode
Definition at line 64 of file args_parser.cpp.
                                                                                              {
    (void) auto_level;
    (void) output_cnt;
    (void) filename;
    (void) voice;
    assert(args_dict);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(auto_level);
    assert(output_cnt);
    assert(filename);
    assert(voice);
    printf("# This program generates text with probabilistic automaton\n"
           "# Console args:\n");
    for (int i = 0; i < args_dict_len; i++)
        printf("%s", args_dict[i].description);
    printf("# End of help.\n");
    return ArgsMode::EXIT;
}
References EXIT.
Referenced by args_parse().
set_filename()
ArgsMode set_filename (const Argument args_dict[], const int args_dict_len, int * arg_i, const int argc, char * argv[], int * auto_level, ssize_t * output_cnt, const char ** filename, bool * voice)
Sets filename.
Parameters
args_dict
args_dict_len
arg_i
argc
argv
auto_level
output_cnt
filename
voice
Returns
ArgsMode
Definition at line 141 of file args_parser.cpp.
                                                                                                {
    (void) args_dict;
    (void) args_dict_len;
    (void) auto_level;
    (void) output_cnt;
    (void) voice;
    assert(args_dict);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(auto_level);
    assert(output_cnt);
    assert(filename);
    assert(voice);
    if (++(*arg_i) >= argc) {
        printf("No filename found\n");
        return ArgsMode::ERR;
    }
    *filename = argv[*arg_i];
    return ArgsMode::CONTINUE;
}
References CONTINUE, and ERR.
Referenced by args_parse().
set_level()
ArgsMode set_level (const Argument args_dict[], const int args_dict_len, int * arg_i, const int argc, char * argv[], int * auto_level, ssize_t * output_cnt, const char ** filename, bool * voice)
Sets auto max level.
Parameters
args_dict
args_dict_len
arg_i
argc
argv
auto_level
output_cnt
filename
voice
Returns
ArgsMode
Definition at line 91 of file args_parser.cpp.
                                                                                             {
    (void) args_dict;
    (void) args_dict_len;
    (void) output_cnt;
    (void) filename;
    (void) voice;
    assert(args_dict);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(auto_level);
    assert(output_cnt);
    assert(filename);
    assert(voice);
    if (++(*arg_i) >= argc || sscanf(argv[*arg_i], "%d", auto_level) != 1) {
        printf("No test level found\n");
        return ArgsMode::ERR;
    }
    return ArgsMode::CONTINUE;
}
References CONTINUE, and ERR.
Referenced by args_parse().
set_symb_num()
ArgsMode set_symb_num (const Argument args_dict[], const int args_dict_len, int * arg_i, const int argc, char * argv[], int * auto_level, ssize_t * output_cnt, const char ** filename, bool * voice)
Sets output symb num.
Parameters
args_dict
args_dict_len
arg_i
argc
argv
auto_level
output_cnt
filename
voice
Returns
ArgsMode
Definition at line 116 of file args_parser.cpp.
                                                                                                {
    (void) args_dict;
    (void) args_dict_len;
    (void) auto_level;
    (void) filename;
    (void) voice;
    assert(args_dict);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(auto_level);
    assert(output_cnt);
    assert(filename);
    assert(voice);
    if (++(*arg_i) >= argc || sscanf(argv[*arg_i], "%zd", output_cnt) != 1) {
        printf("No output symbols number found\n");
        return ArgsMode::ERR;
    }
    return ArgsMode::CONTINUE;
}
References CONTINUE, and ERR.
Referenced by args_parse().