automaton_parser.h File Reference
#include <stdio.h>
#include <random>
#include nodevector.h
Functions
void auto_parse (FILE *file, Nodes *nodes, int max_level)
Parses text from file.
void auto_write_node (Nodes *nodes, const char *ch, const unsigned int level, const unsigned int max_level)
Finds ch Node in Nodes vector and increments it's cnt. Is called recursively for levels from level to max_level.
void auto_generate_rand_node (Nodes *nodes, char *str, const unsigned int level, const unsigned int max_level)
Random generates symbol for levels from level to max_level. Writes to str. Is called recursively.
bool auto_get_node (Nodes *nodes, char *str, const unsigned int level, const unsigned int max_level, const unsigned int rand_max_level)
Finds Node with char from str for all levels from level to max_level. Is called recursively. Then calles auto_generate_rand_node for levels from max_level to rand_max_level.
void auto_detor (Nodes *nodes)
Calls destructors for all vectors in nodes. Is called recursively.
Function Documentation
auto_detor()
void auto_detor (Nodes * nodes)
Calls destructors for all vectors in nodes. Is called recursively.
Parameters
nodes
Definition at line 101 of file automaton_parser.cpp.
                              {
    for (size_t i = 0; i < nodes->vec.size; i++) {
        auto_detor(&nodes->vec.arr[i].children);
    }
    vec_detor(&nodes->vec);
}
References NodeVector::arr, auto_detor(), Node::children, NodeVector::size, Nodes::vec, and vec_detor().
Referenced by auto_detor(), and main().
auto_generate_rand_node()
void auto_generate_rand_node (Nodes * nodes, char * str, const unsigned int level, const unsigned int max_level)
Random generates symbol for levels from level to max_level. Writes to str. Is called recursively.
Parameters
nodes current level Nodes
str destination
level current level
max_level
Definition at line 61 of file automaton_parser.cpp.
                                                                                                              {
    static std::random_device rd;
    // Mersenne twister PRNG, initialized with seed from previous random device instance
    static std::mt19937 gen(rd());
    std::uniform_int_distribution<unsigned long long> rand_normal {0, nodes->all_cnt};
    long long r = (long long)rand_normal(gen);
    for (size_t i = 0; i < nodes->vec.size; i++) {
        r -= nodes->vec.arr[i].cnt;
        if (r < 0) {
            str[level] = nodes->vec.arr[i].ch;
            if (level < max_level)
                auto_generate_rand_node(&nodes->vec.arr[i].children, str, level + 1, max_level);
            break;
        }
    }
}
References Nodes::all_cnt, NodeVector::arr, auto_generate_rand_node(), Node::ch, Node::children, Node::cnt, NodeVector::size, and Nodes::vec.
Referenced by auto_generate_rand_node(), and auto_get_node().
auto_get_node()
bool auto_get_node (Nodes * nodes, char * str, const unsigned int level, const unsigned int max_level, const unsigned int rand_max_level)
Finds Node with char from str for all levels from level to max_level. Is called recursively. Then calles auto_generate_rand_node for levels from max_level to rand_max_level.
Parameters
nodes current level Nodes
str source
level current level
max_level max level and min level for auto_generate_rand_node()
rand_max_level max level for auto_generate_rand_node()
Returns
true success
false failure
Definition at line 82 of file automaton_parser.cpp.
                                                                                                                                       {
    if (level == max_level) {
        auto_generate_rand_node(nodes, str, max_level, rand_max_level);
        return true;
    }
    size_t i = 0;
    for (i = 0; i < nodes->vec.size; i++) {
        if (nodes->vec.arr[i].ch == str[level])
            break;
    }
    if (i == nodes->vec.size) {
        return false;
    }
    return auto_get_node(&nodes->vec.arr[i].children, str, level + 1, max_level, rand_max_level);
}
References NodeVector::arr, auto_generate_rand_node(), auto_get_node(), Node::ch, Node::children, NodeVector::size, and Nodes::vec.
Referenced by auto_get_node(), and main().
auto_parse()
void auto_parse (FILE * file, Nodes * nodes, int max_level)
Parses text from file.
Parameters
file
nodes zero level Nodes
max_level
Definition at line 4 of file automaton_parser.cpp.
                                                               {
    char* bef = (char*)calloc((max_level + 2), sizeof(char));
    if (bef == nullptr) {
        printf("auto_parse(): Memory alloc error\n");
        return;
    }
    int ch = '\0';
    int begin = 0;
    while ((ch = getc(file)) != EOF) {
        //if (!isalpha(ch) && !isdigit(ch) && !isspace(ch)) continue;
        for (ssize_t i = 0; i < max_level; i++)
            bef[i] = bef[i + 1];
        bef[max_level] = (char)ch;
        if (begin < max_level) {
            begin++;
            continue;
        }
        auto_write_node(nodes, bef, 0, max_level);
    }
    free(bef);
}
References auto_write_node().
Referenced by main().
auto_write_node()
void auto_write_node (Nodes * nodes, const char * ch, const unsigned int level, const unsigned int max_level)
Finds ch Node in Nodes vector and increments it's cnt. Is called recursively for levels from level to max_level.
Parameters
nodes current level Nodes
ch char
level current level
max_level
Definition at line 32 of file automaton_parser.cpp.
                                                                                                            {
    nodes->all_cnt++;
    size_t i = 0;
    for (i = 0; i < nodes->vec.size; i++) {
        if (nodes->vec.arr[i].ch == str[level])
            break;
    }
    if (i == nodes->vec.size) {
        Node new_node = {};
        new_node.ch = str[level];
        new_node.cnt = 1;
        vec_ctor(&new_node.children.vec);
        if(!vec_push(&nodes->vec, new_node)) {
            printf("auto_write_node(): Memory alloc error\n");
            return;
        }
    } else {
        nodes->vec.arr[i].cnt++;
    }
    if (level == max_level)
        return;
    auto_write_node(&nodes->vec.arr[i].children, str, level + 1, max_level);
}
References Nodes::all_cnt, NodeVector::arr, auto_write_node(), Node::ch, Node::children, Node::cnt, NodeVector::size, Nodes::vec, vec_ctor(), and vec_push().
Referenced by auto_parse(), and auto_write_node().