cvector.h File Reference
#include <stdlib.h>
#include <string.h>
#include <assert.h>
Classes
struct Vector
Specifies vector.
Functions
bool vec_ctor (Vector *vec, size_t elem_size)
Vector constructor.
void vec_detor (Vector *vec)
NodeVector destructor.
bool vec_realloc (Vector *vec, size_t new_size)
NodeVector memory reallocation.
bool vec_push (Vector *vec, void *elem)
Push to NodeVector.
void * vec_get (Vector *vec, size_t i)
Gets element from vector.
Function Documentation
vec_ctor()
bool vec_ctor (Vector * vec, size_t elem_size)
Vector constructor.
Parameters
vec
elem_size
Returns
true success
false failure
Definition at line 3 of file cvector.cpp.
                                             {
    assert(vec);
    vec->elem_size = elem_size;
    vec->arr = calloc(vec->capacity, vec->elem_size);
    if (vec->arr == nullptr)
        return false;
    return true;
}
References Vector::arr, Vector::capacity, and Vector::elem_size.
Referenced by auto_write_node(), and main().
vec_detor()
void vec_detor (Vector * vec)
NodeVector destructor.
Parameters
vec
Definition at line 13 of file cvector.cpp.
                            {
    assert(vec);
    free(vec->arr);
    vec->arr = nullptr;
    vec->capacity = 0;
}
References Vector::arr, and Vector::capacity.
Referenced by auto_detor().
vec_get()
void * vec_get (Vector * vec, size_t i)
Gets element from vector.
Parameters
vec
i index
Returns
void*
Definition at line 51 of file cvector.cpp.
                                     {
    assert(vec);
    assert(i < vec->size);
    return (char*)vec->arr + i * vec->elem_size;
}
References Vector::arr, and Vector::elem_size.
Referenced by auto_detor(), auto_generate_rand_node(), auto_get_node(), and auto_write_node().
vec_push()
bool vec_push (Vector * vec, void * elem)
Push to NodeVector.
Parameters
vec
elem
Returns
true success
false failure
Definition at line 36 of file cvector.cpp.
                                       {
    assert(vec);
    assert(elem);
    if (vec->size >= vec->capacity &&
        !vec_realloc(vec, vec->capacity * 2)) {
        return false;
    }
    memcpy((char*)vec->arr + vec->size * vec->elem_size, elem, vec->elem_size);
    vec->size++;
    return true;
}
References Vector::arr, Vector::capacity, Vector::elem_size, Vector::size, and vec_realloc().
Referenced by auto_write_node(), and main().
vec_realloc()
bool vec_realloc (Vector * vec, size_t new_size)
NodeVector memory reallocation.
Parameters
vec
new_size
Returns
true success
false failure
Definition at line 21 of file cvector.cpp.
                                               {
    assert(vec);
    void* ptr = vec->arr;
    vec->arr = (void*)realloc(vec->arr, new_size * vec->elem_size);
    if (vec->arr == nullptr) {
        free(ptr);
        return false;
    }
    vec->capacity = new_size;
    return true;
}
References Vector::arr, Vector::capacity, and Vector::elem_size.
Referenced by vec_push().