nodevector.cpp File Reference
#include nodevector.h
Functions
bool vec_ctor (NodeVector *vec)
NodeVector constructor.
void vec_detor (NodeVector *vec)
NodeVector destructor.
bool vec_realloc (NodeVector *vec, size_t new_size)
NodeVector memory reallocation.
bool vec_push (NodeVector *vec, Node elem)
Push to NodeVector.
Function Documentation
vec_ctor()
bool vec_ctor (NodeVector * vec)
NodeVector constructor.
Parameters
vec
Returns
true success
false failure
Definition at line 3 of file nodevector.cpp.
                               {
    vec->arr = (Node*)calloc(vec->capacity, sizeof(Node));
    if (vec->arr == nullptr)
        return false;
    return true;
}
References NodeVector::arr, and NodeVector::capacity.
Referenced by auto_write_node(), and main().
vec_detor()
void vec_detor (NodeVector * vec)
NodeVector destructor.
Parameters
vec
Definition at line 10 of file nodevector.cpp.
                                {
    free(vec->arr);
    vec->arr = nullptr;
    vec->capacity = 0;
}
References NodeVector::arr, and NodeVector::capacity.
Referenced by auto_detor().
vec_push()
bool vec_push (NodeVector * vec, Node elem)
Push to NodeVector.
Parameters
vec
elem
Returns
true success
false failure
Definition at line 29 of file nodevector.cpp.
                                          {
    if (vec->size >= vec->capacity &&
        !vec_realloc(vec, vec->capacity * 2)) {
        return false;
    }
    vec->arr[vec->size++] = elem;
    return true;
}
References NodeVector::arr, NodeVector::capacity, NodeVector::size, and vec_realloc().
Referenced by auto_write_node().
vec_realloc()
bool vec_realloc (NodeVector * vec, size_t new_size)
NodeVector memory reallocation.
Parameters
vec
new_size
Returns
true success
false failure
Definition at line 16 of file nodevector.cpp.
                                                   {
    Node* ptr = vec->arr;
    vec->arr = (Node*)realloc(vec->arr, new_size * sizeof(Node));
    if (vec->arr == nullptr) {
        free(ptr);
        return false;
    }
    vec->capacity = new_size;
    return true;
}
References NodeVector::arr, and NodeVector::capacity.
Referenced by vec_push().