parsers/words_parser.h File Reference
#include <stdio.h>
#include <assert.h>
#include <random>
#include <string.h>
#include ../statuses.h
#include ../cvector.h
#include ../hash.h
#include ../my_string.h
#include ../voiceover.h
Classes
struct Nodes
Contains automaton level data.
struct Node
Contains char information + next level Node.
Functions
bool auto_parse (Vector *tokens, Nodes *nodes, int max_level)
Adds chars to buf. If char =
 or buf is full, calls txSpeak()
bool auto_write_node (Nodes *nodes, char **tokens_arr, const unsigned int level, const unsigned int max_level)
Finds ch Node in Nodes vector and increments it's cnt. Is called recursively for levels from level to max_level.
void auto_generate_rand_node (Nodes *nodes, char **tokens_arr, const unsigned int level, const unsigned int max_level)
Random generates symbol for levels from level to max_level. Writes to str. Is called recursively.
bool auto_get_node (Nodes *nodes, char **tokens_arr, const unsigned int level, const unsigned int max_level, const unsigned int rand_max_level)
Finds Node with char from str for all levels from level to max_level. Is called recursively. Then calles auto_generate_rand_node for levels from max_level to rand_max_level.
void auto_detor (Nodes *nodes)
Calls destructors for all vectors in nodes. Is called recursively.
Status::Statuses auto_generate_text (Nodes *nodes, const int level, ssize_t cnt, const bool voice)
Generates and prints text.
long long rand_normal_generate_ll (long long min, long long max)
Generates random long long number from min to max.
Function Documentation
auto_detor()
void auto_detor (Nodes * nodes)
Calls destructors for all vectors in nodes. Is called recursively.
Parameters
nodes
Definition at line 148 of file words_parser.cpp.
                              {
    assert(nodes);
    for (size_t i = 0; i < nodes->vec.size; i++) {
        auto_detor(&((Node*)vec_get(&nodes->vec, i))->children);
    }
    vec_detor(&nodes->vec);
}
References auto_detor(), Vector::size, Nodes::vec, vec_detor(), and vec_get().
Referenced by auto_detor(), and main().
auto_generate_rand_node()
void auto_generate_rand_node (Nodes * nodes, char ** tokens_arr, const unsigned int level, const unsigned int max_level)
Random generates symbol for levels from level to max_level. Writes to str. Is called recursively.
Parameters
nodes current level Nodes
tokens_arr destination
level current level
max_level
Definition at line 56 of file words_parser.cpp.
                                                                                                                      {
    assert(nodes);
    assert(tokens_arr);
    long long r = rand_normal_generate_ll(0, (long long)nodes->all_cnt);
    for (size_t i = 0; i < nodes->vec.size; i++) {
        r -= ((Node*)vec_get(&nodes->vec, i))->cnt;
        if (r <= 0) {
            tokens_arr[level] = ((Node*)vec_get(&nodes->vec, i))->token;
            if (level < max_level)
                auto_generate_rand_node(&((Node*)vec_get(&nodes->vec, i))->children, tokens_arr, level + 1, max_level);
            return;
        }
    }
    assert(0 && "Rand node generate error");
}
References Nodes::all_cnt, auto_generate_rand_node(), rand_normal_generate_ll(), Vector::size, Nodes::vec, and vec_get().
Referenced by auto_generate_rand_node(), and auto_get_node().
auto_generate_text()
Status::Statuses auto_generate_text (Nodes * nodes, const int level, ssize_t cnt, const bool voice)
Generates and prints text.
Parameters
nodes zero level node
level max level
cnt word count
voice enables voiceover
Returns
Status::Statuses
Definition at line 103 of file words_parser.cpp.
                                                                                                {
    assert(nodes);
    char** prev_tokens = (char**)calloc((level + 1), sizeof(char*));
    if (prev_tokens == nullptr) {
        printf("Memory alloc error\n");
        return Status::MEMORY_EXCEED;
    }
    printf("---------- level %d ----------\n", level);
    auto_get_node(nodes, prev_tokens, 0, 0, level);
    int downgrade = 0;
    while (--cnt > 0) {
        for (ssize_t i = 0; i < level; i++)
            prev_tokens[i] = prev_tokens[i + 1];
        while (!auto_get_node(nodes, prev_tokens, 0, level, level) && --cnt > 0) {
            downgrade++;
            if (level < downgrade) downgrade = level;
            auto_get_node(nodes, prev_tokens, 0, level - downgrade, level);
            printf("%s ", prev_tokens[0]);
            if (voice)
                speak_add_token(prev_tokens[0]);
            for (ssize_t i = 0; i < level; i++)
                prev_tokens[i] = prev_tokens[i + 1];
        }
        printf("%s ", prev_tokens[0]);
        if (voice)
            speak_add_token(prev_tokens[0]);
        downgrade = 0;
    }
    speak_add_token("", true);
    printf("\n---------- stop ----------\n");
    free(prev_tokens);
    return Status::NORMAL_WORK;
}
References auto_get_node(), Status::MEMORY_EXCEED, Status::NORMAL_WORK, and speak_add_token().
Referenced by main().
auto_get_node()
bool auto_get_node (Nodes * nodes, char ** tokens_arr, const unsigned int level, const unsigned int max_level, const unsigned int rand_max_level)
Finds Node with char from str for all levels from level to max_level. Is called recursively. Then calles auto_generate_rand_node for levels from max_level to rand_max_level.
Parameters
nodes current level Nodes
tokens_arr source
level current level
max_level max level and min level for auto_generate_rand_node()
rand_max_level max level for auto_generate_rand_node()
Returns
true success
false failure
Definition at line 75 of file words_parser.cpp.
                                                                                                                                               {
    assert(nodes);
    assert(tokens_arr);
    if (level == max_level) {
        auto_generate_rand_node(nodes, tokens_arr, max_level, rand_max_level);
        return true;
    }
    size_t i = 0;
    char* token = tokens_arr[level];
    size_t token_len = strlen(token);
    for (i = 0; i < nodes->vec.size; i++) {
        size_t node_token_len = strlen(((Node*)vec_get(&nodes->vec, i))->token);
        if (node_token_len == token_len &&
            ((Node*)vec_get(&nodes->vec, i))->hash == MurmurHash2A(token, (int)token_len) &&
            strncmp(((Node*)vec_get(&nodes->vec, i))->token, token, node_token_len))
                break;
    }
    if (i == nodes->vec.size) {
        return false;
    }
    return auto_get_node(&((Node*)vec_get(&nodes->vec, i))->children, tokens_arr, level + 1, max_level, rand_max_level);
}
References auto_generate_rand_node(), auto_get_node(), MurmurHash2A(), Vector::size, Nodes::vec, and vec_get().
Referenced by auto_generate_text(), and auto_get_node().
auto_parse()
bool auto_parse (Vector * tokens, Nodes * nodes, int max_level)
Adds chars to buf. If char =
 or buf is full, calls txSpeak()
Parameters
buf
ch
Parses tokens to nodes
Parameters
tokens
nodes zero level Nodes
max_level
Returns
true success
false error
Definition at line 3 of file words_parser.cpp.
                                                             {
    assert(tokens);
    assert(nodes);
    for (size_t i = 0; i < tokens->size - max_level; i++) {
        if (!auto_write_node(nodes, (char**)(tokens->arr) + i, 0, max_level))
            return false;
    }
    return true;
}
References Vector::arr, auto_write_node(), and Vector::size.
Referenced by main().
auto_write_node()
bool auto_write_node (Nodes * nodes, char ** tokens_arr, const unsigned int level, const unsigned int max_level)
Finds ch Node in Nodes vector and increments it's cnt. Is called recursively for levels from level to max_level.
Parameters
nodes current level Nodes
tokens_arr source
level current level
max_level
Returns
true success
false error
Definition at line 14 of file words_parser.cpp.
                                                                                                              {
    assert(nodes);
    assert(tokens_arr);
    nodes->all_cnt++;
    size_t i = 0;
    size_t token_len = strlen(tokens_arr[level]);
    for (i = 0; i < nodes->vec.size; i++) {
        size_t node_token_len = strlen(((Node*)vec_get(&nodes->vec, i))->token);
        if (node_token_len == token_len &&
            ((Node*)vec_get(&nodes->vec,i))->hash == MurmurHash2A(tokens_arr[level], (int)token_len) &&
            strncmp(((Node*)vec_get(&nodes->vec, i))->token, tokens_arr[level], node_token_len))
                break;
    }
    if (i == nodes->vec.size) {
        Node new_node = {};
        new_node.token = tokens_arr[level];
        new_node.hash = MurmurHash2A(new_node.token, (int)token_len);
        new_node.cnt = 1;
        if (!vec_ctor(&new_node.children.vec, sizeof(Node))) {
            printf("auto_write_node(): Memory alloc error\n");
            return false;
        }
        if(!vec_push(&nodes->vec, &new_node)) {
            printf("auto_write_node(): Memory alloc error\n");
            return false;
        }
    } else {
        ((Node*)vec_get(&nodes->vec, i))->cnt++;
    }
    if (level == max_level)
        return true;
    return auto_write_node(&((Node*)vec_get(&nodes->vec, i))->children, tokens_arr, level + 1, max_level);
}
References Nodes::all_cnt, auto_write_node(), Node::children, Node::cnt, Node::hash, MurmurHash2A(), Vector::size, Node::token, Nodes::vec, vec_ctor(), vec_get(), and vec_push().
Referenced by auto_parse(), and auto_write_node().
rand_normal_generate_ll()
long long rand_normal_generate_ll (long long min, long long max)
Generates random long long number from min to max.
Parameters
min
max
Returns
long long
Definition at line 157 of file words_parser.cpp.
                                                                {
    static std::random_device rd;
    // Mersenne twister PRNG, initialized with seed from previous random device instance
    static std::mt19937 gen(rd());
    std::uniform_int_distribution<long long> rand_normal {min, max};
    return rand_normal(gen);
}
Referenced by auto_generate_rand_node().